import { describe, it, expect } from 'vitest';
import { generateMockFactory } from '../src/templates/mockFactory';
import { createMockDMMFModel, createMockDMMFField, createMockDMMF } from './test-helpers';

describe('mockFactory with default values', () => {
  it('should use static string default values when no annotation', () => {
    const model = createMockDMMFModel({
      name: 'User',
      fields: [
        createMockDMMFField({
          name: 'role',
          type: 'String',
          hasDefaultValue: true,
          default: 'USER',
        }),
        createMockDMMFField({
          name: 'status',
          type: 'String',
          hasDefaultValue: true,
          default: 'active',
        }),
      ],
    });

    const dmmf = createMockDMMF();
    const config = { createZodSchemas: false, mockDateRange: 30 };

    const result = generateMockFactory(model, config, dmmf);

    expect(result).toContain("role: 'USER'");
    expect(result).toContain("status: 'active'");
  });

  it('should use numeric default values', () => {
    const model = createMockDMMFModel({
      name: 'Product',
      fields: [
        createMockDMMFField({
          name: 'stock',
          type: 'Int',
          hasDefaultValue: true,
          default: 100,
        }),
        createMockDMMFField({
          name: 'price',
          type: 'Float',
          hasDefaultValue: true,
          default: 99.99,
        }),
      ],
    });

    const dmmf = createMockDMMF();
    const config = { createZodSchemas: false, mockDateRange: 30 };

    const result = generateMockFactory(model, config, dmmf);

    expect(result).toContain('stock: 100');
    expect(result).toContain('price: 99.99');
  });

  it('should use boolean default values', () => {
    const model = createMockDMMFModel({
      name: 'Settings',
      fields: [
        createMockDMMFField({
          name: 'emailNotifications',
          type: 'Boolean',
          hasDefaultValue: true,
          default: true,
        }),
        createMockDMMFField({
          name: 'marketingEmails',
          type: 'Boolean',
          hasDefaultValue: true,
          default: false,
        }),
      ],
    });

    const dmmf = createMockDMMF();
    const config = { createZodSchemas: false, mockDateRange: 30 };

    const result = generateMockFactory(model, config, dmmf);

    expect(result).toContain('emailNotifications: true');
    expect(result).toContain('marketingEmails: false');
  });

  it('should handle function defaults', () => {
    const model = createMockDMMFModel({
      name: 'Post',
      fields: [
        createMockDMMFField({
          name: 'id',
          type: 'String',
          hasDefaultValue: true,
          default: { name: 'cuid', args: [] },
        }),
        createMockDMMFField({
          name: 'createdAt',
          type: 'DateTime',
          hasDefaultValue: true,
          default: { name: 'now', args: [] },
        }),
      ],
    });

    const dmmf = createMockDMMF();
    const config = { createZodSchemas: false, mockDateRange: 30 };

    const result = generateMockFactory(model, config, dmmf);

    expect(result).toContain('id: faker.string.nanoid()');
    expect(result).toContain('createdAt: new Date()');
  });

  it('should prioritize @mock annotation over default value', () => {
    const model = createMockDMMFModel({
      name: 'User',
      fields: [
        createMockDMMFField({
          name: 'role',
          type: 'String',
          hasDefaultValue: true,
          default: 'USER',
          documentation: '@mock "ADMIN"',
        }),
      ],
    });

    const dmmf = createMockDMMF();
    const config = { createZodSchemas: false, mockDateRange: 30 };

    const result = generateMockFactory(model, config, dmmf);

    expect(result).toContain('role: "ADMIN"');
    expect(result).not.toContain("role: 'USER'");
  });

  it('should fall back to semantic analysis when no default or annotation', () => {
    const model = createMockDMMFModel({
      name: 'User',
      fields: [
        createMockDMMFField({
          name: 'email',
          type: 'String',
          hasDefaultValue: false,
        }),
      ],
    });

    const dmmf = createMockDMMF();
    const config = { createZodSchemas: false, mockDateRange: 30 };

    const result = generateMockFactory(model, config, dmmf);

    expect(result).toContain('email: faker.internet.email()');
  });

  it('should handle dbgenerated by falling back to semantic analysis', () => {
    const model = createMockDMMFModel({
      name: 'User',
      fields: [
        createMockDMMFField({
          name: 'sequenceId',
          type: 'Int',
          hasDefaultValue: true,
          default: { name: 'dbgenerated', args: ['nextval("user_sequence")'] },
        }),
      ],
    });

    const dmmf = createMockDMMF();
    const config = { createZodSchemas: false, mockDateRange: 30 };

    const result = generateMockFactory(model, config, dmmf);

    // Should fall back to generic Int generation
    expect(result).toContain('sequenceId: faker.number.int({ min: 1, max: 1000 })');
  });
});